print("Hello World")
variable = "WHAT IS GOING ON?"
phrase = "I am going to live happily"
print (variable + " nothing much\neverything is awesome")
print(variable.lower())
print(variable.upper())
print(variable.isupper())
print(variable.islower())
print(variable.upper().isupper())
print(variable.upper().islower())
print(len(variable))
print(variable[0])
print(variable[1])
print(variable[3])
print(variable[5])
print(variable[8])
print(variable[9])
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.islower())
print(len(phrase))
print(phrase[3])
print(phrase[2])
print(phrase[0])
print(variable.index("H"))
print(phrase.index("a"))
print(variable.index("GOING"))
print(variable.index("IS"))
print(len(variable))
print(variable.index("G"))
print(phrase.index("hap"))
phrases = "Giraffe Academy"
print(phrases.replace("Giraffe", "Fucking Amazing"))
print(2+2)
print(3*(4+5))
print(10%3)
my_num=-5
print(my_num)
print(str(my_num) + "is my favourite number")
print(abs(my_num))
print(pow(3,2))
print(max(2,10))
print(min(100,200))
print(round(3.2))
print(round(3.71223424))
from math import*
print(floor(3.7))
print(ceil(3.2))
print(sqrt(89))
name = input("Enter your name: ")
age = input("Enter your age: ")
say = input("name the person you like the most: ")
print("hello " + name + " you are " + age + " and you like Harsh very much ")
num1 = input("Enter a number: ")
num2 = input("Enter another number: ")
result = int(num1) +int(num2)
print (result)
